spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#mybatis-plus:
#  mapper-locations: classpath:mybatis/mapper/*xml
#  config-location: classpath:mybatis/config/mybatis-config.xml